/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Christian.auca.rw.view;

import java.awt.Color;

/**
 *
 * @author B Christian
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    
    Color DefaultColor,ClickedColor;
    public AdminDashboard() {
        initComponents();
        
        DefaultColor=new Color(0,51,51);
        ClickedColor= new Color(240,151,57);
        
        // Set default color to pan on run time 
        AdminLabel.setBackground(DefaultColor);
        CatLabel.setBackground(DefaultColor);
        SystLabel.setBackground(DefaultColor);
        UserLabel.setBackground(DefaultColor);
        TaskLabel.setBackground(DefaultColor);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        AdminLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        SystLabel = new javax.swing.JLabel();
        TaskLabel = new javax.swing.JLabel();
        CatLabel = new javax.swing.JLabel();
        TestingButton = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1129, 929));
        setUndecorated(true);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-administrator-64.png")); // NOI18N
        jLabel2.setText("   WELCOME TO ADMINISTRATION ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-exit-cute-outline\\icons8-exit-50.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-system-administrator-others\\icons8-system-administrator-50.png")); // NOI18N
        jLabel3.setText("TASK MANAGEMENT SYSTEM ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1119, -1));
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        AdminLabel.setBackground(new java.awt.Color(0, 51, 51));
        AdminLabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-menu-ios-17-filled\\icons8-menu-50.png")); // NOI18N
        AdminLabel.setText("Manage Admins");
        AdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminLabelMousePressed(evt);
            }
        });

        UserLabel.setBackground(new java.awt.Color(0, 51, 51));
        UserLabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-menu-ios-17-filled\\icons8-menu-50.png")); // NOI18N
        UserLabel.setText("Manage Users");
        UserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UserLabelMousePressed(evt);
            }
        });

        SystLabel.setBackground(new java.awt.Color(0, 51, 51));
        SystLabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        SystLabel.setForeground(new java.awt.Color(255, 255, 255));
        SystLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-menu-ios-17-filled\\icons8-menu-50.png")); // NOI18N
        SystLabel.setText("System Administration");
        SystLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SystLabelMousePressed(evt);
            }
        });

        TaskLabel.setBackground(new java.awt.Color(0, 51, 51));
        TaskLabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        TaskLabel.setForeground(new java.awt.Color(255, 255, 255));
        TaskLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-menu-ios-17-filled\\icons8-menu-50.png")); // NOI18N
        TaskLabel.setText("Task Management");
        TaskLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaskLabelMousePressed(evt);
            }
        });

        CatLabel.setBackground(new java.awt.Color(0, 51, 51));
        CatLabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        CatLabel.setForeground(new java.awt.Color(255, 255, 255));
        CatLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-menu-ios-17-filled\\icons8-menu-50.png")); // NOI18N
        CatLabel.setText("Category and Priority");
        CatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CatLabelMousePressed(evt);
            }
        });

        TestingButton.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        TestingButton.setForeground(new java.awt.Color(255, 255, 255));
        TestingButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-menu-ios-17-filled\\icons8-menu-50.png")); // NOI18N
        TestingButton.setText("Settings");
        TestingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TestingButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SystLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(TaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TestingButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(TaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(CatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(SystLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(TestingButton)
                .addGap(102, 102, 102))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, -1, 803));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 126, -1, 800));
        jTabbedPane1.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void AdminLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLabelMousePressed
        // TODO add your handling code here:
           AdminLabel.setBackground(ClickedColor);
           CatLabel.setBackground(DefaultColor);
           SystLabel.setBackground(DefaultColor);
           UserLabel.setBackground(DefaultColor);
           TaskLabel.setBackground(DefaultColor);
           
           
    }//GEN-LAST:event_AdminLabelMousePressed

    private void UserLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLabelMousePressed
        // TODO add your handling code here:
        AdminLabel.setBackground(DefaultColor);
        CatLabel.setBackground(DefaultColor);
        SystLabel.setBackground(DefaultColor);
        UserLabel.setBackground(ClickedColor);
        TaskLabel.setBackground(DefaultColor);
    }//GEN-LAST:event_UserLabelMousePressed

    private void TaskLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskLabelMousePressed
        // TODO add your handling code here:
        AdminLabel.setBackground(DefaultColor);
        CatLabel.setBackground(DefaultColor);
        SystLabel.setBackground(DefaultColor);
        UserLabel.setBackground(DefaultColor);
        TaskLabel.setBackground(ClickedColor);
    }//GEN-LAST:event_TaskLabelMousePressed

    private void CatLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatLabelMousePressed
        // TODO add your handling code here:
        AdminLabel.setBackground(DefaultColor);
        CatLabel.setBackground(ClickedColor);
        SystLabel.setBackground(DefaultColor);
        UserLabel.setBackground(DefaultColor);
        TaskLabel.setBackground(DefaultColor);
    }//GEN-LAST:event_CatLabelMousePressed

    private void SystLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SystLabelMousePressed
        // TODO add your handling code here:
        AdminLabel.setBackground(DefaultColor);
        CatLabel.setBackground(DefaultColor);
        SystLabel.setBackground(ClickedColor);
        UserLabel.setBackground(DefaultColor);
        TaskLabel.setBackground(DefaultColor);
    }//GEN-LAST:event_SystLabelMousePressed

    private void AdminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLabelMouseClicked
        // TODO add your handling code here:
        OtherAdmin otheradmin = new OtherAdmin();
        otheradmin.setVisible(true);
        otheradmin.admin_display();
        this.setVisible(false);
      
    }//GEN-LAST:event_AdminLabelMouseClicked

    private void UserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserLabelMouseClicked
        // TODO add your handling code here:
       jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_UserLabelMouseClicked

    private void TestingButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestingButtonMousePressed
        // TODO add your handling code here:
         // TODO add your handling code here:
        AdminLabel.setBackground(DefaultColor);
        CatLabel.setBackground(DefaultColor);
        TestingButton.setBackground(ClickedColor);
        UserLabel.setBackground(DefaultColor);
        TaskLabel.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_TestingButtonMousePressed

    private void TaskLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskLabelMouseClicked
        // TODO add your handling code here:
        
        TaskView taskview = new TaskView();
        taskview.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TaskLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JLabel CatLabel;
    private javax.swing.JLabel SystLabel;
    private javax.swing.JLabel TaskLabel;
    private javax.swing.JLabel TestingButton;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
